# Generated by Django 2.2 on 2019-06-07 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_auto_20190601_2206'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookInstance',
            new_name='BooksInstance',
        ),
    ]
