# Generated by Django 2.2 on 2019-07-13 18:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_auto_20190607_0030'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BooksInstance',
            new_name='BookInstance',
        ),
    ]
